# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import kv_pb2 as kv__pb2


class KVServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Put = channel.unary_unary(
        '/kv.KVService/Put',
        request_serializer=kv__pb2.PutRequest.SerializeToString,
        response_deserializer=kv__pb2.PutResponse.FromString,
        )
    self.StreamPut = channel.stream_unary(
        '/kv.KVService/StreamPut',
        request_serializer=kv__pb2.PutRequest.SerializeToString,
        response_deserializer=kv__pb2.PutResponse.FromString,
        )
    self.Get = channel.unary_unary(
        '/kv.KVService/Get',
        request_serializer=kv__pb2.GetRequest.SerializeToString,
        response_deserializer=kv__pb2.GetResponse.FromString,
        )
    self.Delete = channel.unary_unary(
        '/kv.KVService/Delete',
        request_serializer=kv__pb2.DeleteRequest.SerializeToString,
        response_deserializer=kv__pb2.DeleteResponse.FromString,
        )
    self.Search = channel.unary_unary(
        '/kv.KVService/Search',
        request_serializer=kv__pb2.SearchRequest.SerializeToString,
        response_deserializer=kv__pb2.SearchResponse.FromString,
        )
    self.Heartbeat = channel.unary_unary(
        '/kv.KVService/Heartbeat',
        request_serializer=kv__pb2.HeartbeatRequest.SerializeToString,
        response_deserializer=kv__pb2.HeartbeatResponse.FromString,
        )
    self.Sync = channel.unary_unary(
        '/kv.KVService/Sync',
        request_serializer=kv__pb2.SyncRequest.SerializeToString,
        response_deserializer=kv__pb2.SyncResponse.FromString,
        )


class KVServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Put(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StreamPut(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Get(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Delete(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Search(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Heartbeat(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Sync(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_KVServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Put': grpc.unary_unary_rpc_method_handler(
          servicer.Put,
          request_deserializer=kv__pb2.PutRequest.FromString,
          response_serializer=kv__pb2.PutResponse.SerializeToString,
      ),
      'StreamPut': grpc.stream_unary_rpc_method_handler(
          servicer.StreamPut,
          request_deserializer=kv__pb2.PutRequest.FromString,
          response_serializer=kv__pb2.PutResponse.SerializeToString,
      ),
      'Get': grpc.unary_unary_rpc_method_handler(
          servicer.Get,
          request_deserializer=kv__pb2.GetRequest.FromString,
          response_serializer=kv__pb2.GetResponse.SerializeToString,
      ),
      'Delete': grpc.unary_unary_rpc_method_handler(
          servicer.Delete,
          request_deserializer=kv__pb2.DeleteRequest.FromString,
          response_serializer=kv__pb2.DeleteResponse.SerializeToString,
      ),
      'Search': grpc.unary_unary_rpc_method_handler(
          servicer.Search,
          request_deserializer=kv__pb2.SearchRequest.FromString,
          response_serializer=kv__pb2.SearchResponse.SerializeToString,
      ),
      'Heartbeat': grpc.unary_unary_rpc_method_handler(
          servicer.Heartbeat,
          request_deserializer=kv__pb2.HeartbeatRequest.FromString,
          response_serializer=kv__pb2.HeartbeatResponse.SerializeToString,
      ),
      'Sync': grpc.unary_unary_rpc_method_handler(
          servicer.Sync,
          request_deserializer=kv__pb2.SyncRequest.FromString,
          response_serializer=kv__pb2.SyncResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'kv.KVService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
